### ISSUE TITLE
S社のエリア拡大

### ISSUE THREAD

**Issue by Shige-Matsuo** [berlitz-jpn/Test#1]
地方への拡大について時期と内容を正確に把握しておきたい。

**Comment by Yachiyo-Nakajima** [comment]
先ほどの資料では不十分でしょうか？

**Comment by Yachiyo-Nakajima** [comment]
先ほどの資料では不十分でしょうか？

**Comment by Shige-Matsuo** [comment]
展開県数や今後の継続性等はわかりますかね？

あとこの資料についてもアップしてください
https://github.com/berlitz-jpn/Test/issues/1#issuecomment-495476196

**Comment by Yachiyo-Nakajima** [comment]
先ほどの話は、あくまでもT4の期間に販社の一部門が加わる前提の話なので、全体像は更に確認が必要かと思います。今後についてはPJ終了後がまだ不透明ですので。。。

**Comment by Shige-Matsuo** [comment]
なるほど。
じゃ10日程、たったら再度オープンします！

**Comment by Shige-Matsuo** [comment]
[190522_基礎力トレーニングプログラム第4ターム地方拠点実施方法ご提案.pptx](https://github.com/berlitz-jpn/Test/files/3215231/190522_.4.pptx)

資料添付も簡単です。
