### ISSUE TITLE
ユーザー名の変更はどうやるのでしょうか？

### ISSUE THREAD

**Issue by Shige-Matsuo** [berlitz-jpn/Test#2]
@Yachiyo-Nakajima 
Berlitz-Japanが私のユーザー名になってしまいました。
どうやって変更するのでしょうか？

**Comment by Yachiyo-Nakajima** [comment]
テスト

**Comment by Yachiyo-Nakajima** [comment]
テスト

**Comment by Shige-Matsuo** [comment]
全てメールが入りますがNotification設定もありますよね？

**Comment by Yachiyo-Nakajima** [comment]
https://www.karelie.net/github-change-user-name/
これで変えてみたんですが、変わりませんね。。。
プロファイルページは変わってますが。。。

横のところでNotificationのSubscribe/unsubscribeを自分で選べるようです。

**Comment by Yachiyo-Nakajima** [comment]
https://www.karelie.net/github-change-user-name/
これで変えてみたんですが、変わりませんね。。。
プロファイルページは変わってますが。。。

横のところでNotificationのSubscribe/unsubscribeを自分で選べるようです。

**Comment by Yachiyo-Nakajima** [comment]
あれ、松尾さん変わりましたね？＜ユーザー名

**Comment by Shige-Matsuo** [comment]
出来ました！！
:clap:
